# Generated by Django 4.2.1 on 2023-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="CPF"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Birth Date"
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Mobile Phone"
            ),
        ),
    ]
