# Generated by Django 4.2.1 on 2023-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_usuario_cpf_usuario_data_nascimento_usuario_telefone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="data_nascimento",
            field=models.DateField(blank=True, null=True, verbose_name="Birth Date"),
        ),
    ]
